package com.example.administrator.thefirstnavigation.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.thefirstnavigation.bean.GreenBean.HistoryBean;
import com.example.administrator.thefirstnavigation.bean.GreenBean.LoginBean;
import com.example.administrator.thefirstnavigation.bean.GreenBean.SeclectorBean;

import com.example.administrator.thefirstnavigation.dao.HistoryBeanDao;
import com.example.administrator.thefirstnavigation.dao.LoginBeanDao;
import com.example.administrator.thefirstnavigation.dao.SeclectorBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyBeanDaoConfig;
    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig seclectorBeanDaoConfig;

    private final HistoryBeanDao historyBeanDao;
    private final LoginBeanDao loginBeanDao;
    private final SeclectorBeanDao seclectorBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyBeanDaoConfig = daoConfigMap.get(HistoryBeanDao.class).clone();
        historyBeanDaoConfig.initIdentityScope(type);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        seclectorBeanDaoConfig = daoConfigMap.get(SeclectorBeanDao.class).clone();
        seclectorBeanDaoConfig.initIdentityScope(type);

        historyBeanDao = new HistoryBeanDao(historyBeanDaoConfig, this);
        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        seclectorBeanDao = new SeclectorBeanDao(seclectorBeanDaoConfig, this);

        registerDao(HistoryBean.class, historyBeanDao);
        registerDao(LoginBean.class, loginBeanDao);
        registerDao(SeclectorBean.class, seclectorBeanDao);
    }
    
    public void clear() {
        historyBeanDaoConfig.clearIdentityScope();
        loginBeanDaoConfig.clearIdentityScope();
        seclectorBeanDaoConfig.clearIdentityScope();
    }

    public HistoryBeanDao getHistoryBeanDao() {
        return historyBeanDao;
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public SeclectorBeanDao getSeclectorBeanDao() {
        return seclectorBeanDao;
    }

}
